### ISSUE TITLE
environment.Lamby.cmd

### ISSUE THREAD

**Issue by hopewise** [rails-lambda/lamby-cookiecutter#30]
Hello

Where can I find `config/environment.Lamby.cmd` file ?

**Comment by metaskills** [comment]
The Lambda Runtime Interface Client (RIC) parses that `config/environment.Lamby.cmd` string into two key areas. They are:

* `config/environment` - Which has an implicit `.rb` extension so it becomes `config/environment.rb`. The RIC will load this file. That file is standard in Rails for loading the application.
* `Lamby.cmd` - Is the method the RIC invokes once it has loaded your application file. Since this is Rails and every constant is public. This is essentially a method in the Lamby project. See here. https://github.com/customink/lamby/blob/master/lib/lamby.rb#L23-L27

Does that help? Your question relates to this issue I created too. 

* https://github.com/customink/lamby/issues/138
